# ASCII pixel art -> WASM-4 2BPP sprite bytes -> MoonBit source
# Chars: . = transparent, 0..3 = palette color index
import sys

ART = {
"bird_red": r'''
..0000..
.011110.
0111111.
0111a11.
01111110
.011110.
..222...
..2..2..
''',
"bird_yellow": r'''
..0000..
.011110.
0111111.
0111a11.
01111110
.011110.
..222...
..2..2..
''',
"bird_blue": r'''
..0000..
.011110.
0111111.
0111a11.
01111110
.011110.
..222...
..2..2..
''',
"bird_black": r'''
..0000..
.011110.
0111111.
0111a11.
01111110
.011110.
..222...
..2..2..
''',
"pig": r'''
..0000..
.011110.
01111110
0a1b1b10
01111110
011nn110
.011110.
..0000..
''',
"tnt": r'''
11111111
11111111
22222222
22222222
22222222
22222222
11111111
11111111
''',
"cloud": r'''
...0000.....
..0111100...
.011111110..
01111111110.
.01111110...
...0000.....
''',
"bush": r'''
..00000..
.0111110.
011111110
011111110
.0111110.
..00000..
''',
}

# per-sprite palette mapping: char -> palette index (1..3); 0 reserved transparent
PAL = {
    "bird_red":    {'0': 4, '1': 2, '2': 4, 'a': 1},
    "bird_yellow": {'0': 4, '1': 3, '2': 4, 'a': 1},
    "bird_blue":   {'0': 4, '1': 2, '2': 4, 'a': 1},
    "bird_black":  {'0': 4, '1': 4, '2': 4, 'a': 2},
    "pig":         {'0': 4, '1': 3, '2': 4, 'a': 1, 'b': 4, 'n': 1},
    "tnt":         {'1': 2, '2': 1},
    "cloud":       {'0': 1},
    "bush":        {'0': 4, '1': 3},
}

# Palette swapping per bird type: define color index remap at draw time, but 2BPP
# encodes palette slot 1..3 directly, so we bake variant palettes via variant maps.
VARIANT = {
    "bird_yellow": {'1': 3},   # body uses palette slot 3
    "bird_blue":   {'1': 2},
    "bird_black":  {'1': 4 if False else 2},
}

def encode(name, art, pal):
    rows = [r.strip('\n').split('\n') for r in [art]][0]
    rows = [r for r in rows]
    h = len(rows); w = len(rows[0])
    assert all(len(r) == w for r in rows), name
    data = []
    for y in range(0, h, 4):
        for xb in range(0, w, 8):
            for yy in range(y, min(y+4, h)):
                b = 0
                for xx in range(xb, min(xb+8, w)):
                    c = rows[yy][xx]
                    v = 0 if c == '.' else pal[c]
                    b = (b << 2) | v
                data.append(b)
    return w, h, data

out = []
out.append("// Auto-generated by gen_sprites.py — WASM-4 2BPP sprites (4 rows per block of 4 lines)")
out.append("")
for name, art in ART.items():
    pal = dict(PAL[name])
    if name in VARIANT:
        pal.update(VARIANT[name])
    w, h, data = encode(name, art, pal)
    out.append(f"///|")
    out.append(f"pub let {name.upper()}_W : Int = {w}")
    out.append(f"///|")
    out.append(f"pub let {name.upper()}_H : Int = {h}")
    out.append(f"///|")
    out.append(f"pub fn spr_{name}() -> @wasm4.Sprite {{")
    out.append("  @wasm4.sprite([")
    for i in range(0, len(data), 12):
        out.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i+12]) + ",")
    out.append("  ])")
    out.append("}")
    out.append("")
src = "\n".join(out)
open(sys.argv[1] if len(sys.argv) > 1 else "sprites.mbt", "w", encoding="utf-8").write(src)
print(f"OK wrote {len(ART)} sprites")
